#
# Docker compose Datenbank und Webserver
#
# docker compose up -d
# Datenbank init, aktiviere volumes sql-init/ticket.sql - setzt die Daten immer zurück auf Testdaten 
#
name: ticketsystem

services:
  db:
    image: mariadb:latest
    container_name: Datenbank
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: ticketsystem
    ports:
      - "8099:3306"
    volumes:
      - ./mariadbdata:/var/lib/mysql
      - ./sql-init/ticket.sql:/docker-entrypoint-initdb.d/init.sql
#      - C:\Program Files\MariaDB 11.3\data:/var/lib/mysql
    networks:
      - website

  web:
    image: trafex/php-nginx
    container_name: Website
    ports:
      - "8090:8080"
    volumes:
      - ./html:/var/www/html
    networks:
      - website

networks:
  website: