version: '3.8'
 
services:
  db:
    image: mariadb:latest
    container_name: ticketsystem
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: ticketsystem
      MARIADB_USER: my_user
      MARIADB_PASSWORD: my_user_password
    volumes:
      - C:\Program Files\MariaDB 11.3\data:/var/lib/mysql
    networks:
      - website
 
  web:
    image: trafex/php-nginx
    container_name: Website
    ports:
      - "8088:8080"
    volumes:
      - C:\Users\nelo07\source\repos\Docker_347:/var/www/html
    networks:
      - website
 
volumes:
 ticketsystem_data:
 
networks:
  website: